-- Hand-authored to match prisma/schema.prisma's AuditEventIndex model.
--
-- Normally this file is generated by `prisma migrate dev --name init` (see
-- root CONVENTIONS.md, "Migration convention"). In this build's sandbox,
-- `prisma generate`/`migrate dev` cannot reach binaries.prisma.sh (blocked
-- by outbound egress policy — confirmed as a policy denial via the agent
-- proxy status endpoint, not a transient issue) to fetch the schema-engine
-- binary that produces this file automatically. This SQL is written to be
-- byte-for-byte what Prisma would generate for the schema below it, so:
--   1. it can be applied directly (`psql ... -f migration.sql`) to unblock
--      local development/testing right now, and
--   2. once `prisma migrate dev` can run in an environment with real network
--      access, it will detect this migration as already applied (same
--      schema shape) rather than generating a duplicate — or, if preferred,
--      delete this hand-authored file and regenerate from schema.prisma
--      directly. See BUILD_LOG/audit-log.md for the full explanation.

CREATE TABLE "audit_log"."audit_event_index" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actorPrincipalType" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "immudbKey" TEXT NOT NULL,
    "immudbTxId" TEXT NOT NULL,
    "nashKeyId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_event_index_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_event_index_subjectType_subjectId_idx" ON "audit_log"."audit_event_index"("subjectType", "subjectId");

CREATE INDEX "audit_event_index_type_idx" ON "audit_log"."audit_event_index"("type");
