-- Hand-authored to match prisma/schema.prisma's Referral, ComplianceFlag,
-- ComplianceRule, and AuditOutbox models.
--
-- Normally this file is generated by `prisma migrate dev --name init` (see
-- root CONVENTIONS.md, "Migration convention"). In this build's sandbox,
-- `prisma generate`/`migrate dev` cannot reach binaries.prisma.sh (blocked
-- by outbound egress policy — confirmed via the agent proxy status endpoint
-- as a policy denial, not a transient issue, matching the identical,
-- already-documented gap in BUILD_LOG/audit-log.md,
-- BUILD_LOG/identity-access.md, and BUILD_LOG/gp-authorisation.md). This SQL
-- is written to be byte-for-byte what Prisma would generate for the schema
-- below it, so:
--   1. it can be applied directly (`psql ... -f migration.sql`) to unblock
--      local development/testing right now, and
--   2. once `prisma migrate dev` can run in an environment with real network
--      access, it will detect this migration as already applied (same
--      schema shape) rather than generating a duplicate — or, if preferred,
--      delete this hand-authored file and regenerate from schema.prisma
--      directly. See BUILD_LOG/referral.md for the full explanation.

CREATE TABLE "referral"."referral" (
    "id" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "gpId" TEXT NOT NULL,
    "specialistId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'queued',
    "origin" TEXT NOT NULL,
    "urgent" BOOLEAN NOT NULL DEFAULT false,
    "reasonForReferral" TEXT NOT NULL,
    "aiStructuredSummary" JSONB,
    "gpState" TEXT NOT NULL,
    "patientIsMinor" BOOLEAN NOT NULL DEFAULT false,
    "dvIndicated" BOOLEAN NOT NULL DEFAULT false,
    "complexCase" BOOLEAN NOT NULL DEFAULT false,
    "consentGrants" JSONB NOT NULL DEFAULT '[]',
    "queueExpiresAt" TIMESTAMP(3),
    "lapsedAt" TIMESTAMP(3),
    "routedAt" TIMESTAMP(3),
    "declinedAt" TIMESTAMP(3),
    "declinedReason" TEXT,
    "bookedAt" TIMESTAMP(3),
    "reviewStartedAt" TIMESTAMP(3),
    "resolvedEconsultAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "cancelledAt" TIMESTAMP(3),
    "cancelledReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "referral_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "referral_patientId_idx" ON "referral"."referral"("patientId");
CREATE INDEX "referral_gpId_idx" ON "referral"."referral"("gpId");
CREATE INDEX "referral_status_idx" ON "referral"."referral"("status");
CREATE INDEX "referral_status_queueExpiresAt_idx" ON "referral"."referral"("status", "queueExpiresAt");

CREATE TABLE "referral"."compliance_flag" (
    "id" TEXT NOT NULL,
    "referralId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "jurisdiction" TEXT NOT NULL,
    "rulesetVersion" TEXT NOT NULL,
    "checklistPresentedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "checklistAcknowledgedAt" TIMESTAMP(3),
    "acknowledgementNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "compliance_flag_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "compliance_flag_referralId_idx" ON "referral"."compliance_flag"("referralId");

ALTER TABLE "referral"."compliance_flag"
    ADD CONSTRAINT "compliance_flag_referralId_fkey"
    FOREIGN KEY ("referralId") REFERENCES "referral"."referral"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "referral"."compliance_rule" (
    "id" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "jurisdiction" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "triggerCondition" TEXT NOT NULL,
    "checklistText" TEXT NOT NULL,
    "requiresWwcc" BOOLEAN NOT NULL DEFAULT false,
    "exemptForAhpraRegistered" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "effectiveTo" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_rule_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "compliance_rule_category_jurisdiction_version_key" ON "referral"."compliance_rule"("category", "jurisdiction", "version");
CREATE INDEX "compliance_rule_category_jurisdiction_active_idx" ON "referral"."compliance_rule"("category", "jurisdiction", "active");

CREATE TABLE "referral"."audit_outbox" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actor" JSONB NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_outbox_publishedAt_idx" ON "referral"."audit_outbox"("publishedAt");
