-- Hand-authored to match prisma/schema.prisma's CalendarConnection, Slot,
-- Booking, WaitlistEntry, and AuditOutbox models.
--
-- Normally this file is generated by `prisma migrate dev --name init` (see
-- root CONVENTIONS.md, "Migration convention"). In this build's sandbox,
-- `prisma generate`/`migrate dev` cannot reach binaries.prisma.sh (blocked
-- by outbound egress policy — confirmed via the agent proxy status endpoint
-- as a policy denial, not a transient issue, matching the identical,
-- already-documented gap in BUILD_LOG/referral.md, BUILD_LOG/audit-log.md,
-- BUILD_LOG/identity-access.md, and BUILD_LOG/gp-authorisation.md). This SQL
-- is written to be byte-for-byte what Prisma would generate for the schema
-- above it, so:
--   1. it can be applied directly (`psql ... -f migration.sql`) to unblock
--      local development/testing right now — and in fact WAS applied
--      directly against this sandbox's real local Postgres (schema
--      `booking`, already created by infra/postgres/init-schemas.sql) to
--      run the real concurrency proof in
--      test/slot-concurrency.e2e-spec.ts — see BUILD_LOG/booking.md.
--   2. once `prisma migrate dev` can run in an environment with real network
--      access, it will detect this migration as already applied (same
--      schema shape) rather than generating a duplicate — or, if preferred,
--      delete this hand-authored file and regenerate from schema.prisma
--      directly.

CREATE TABLE "calendar_connection" (
    "id" TEXT NOT NULL,
    "specialistId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "externalCalendarId" TEXT NOT NULL,
    "connected" BOOLEAN NOT NULL DEFAULT true,
    "lastSyncedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "calendar_connection_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "calendar_connection_specialistId_key" ON "calendar_connection"("specialistId");
CREATE INDEX "calendar_connection_provider_idx" ON "calendar_connection"("provider");

CREATE TABLE "slot" (
    "id" TEXT NOT NULL,
    "specialistId" TEXT NOT NULL,
    "startsAt" TIMESTAMP(3) NOT NULL,
    "endsAt" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'open',
    "version" INTEGER NOT NULL DEFAULT 0,
    "bookingId" TEXT,
    "source" TEXT NOT NULL DEFAULT 'calendar_sync',
    "externalEventId" TEXT,
    "calendarConnectionId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "slot_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "slot_bookingId_key" ON "slot"("bookingId");
CREATE UNIQUE INDEX "slot_specialistId_startsAt_key" ON "slot"("specialistId", "startsAt");
CREATE INDEX "slot_specialistId_status_startsAt_idx" ON "slot"("specialistId", "status", "startsAt");

ALTER TABLE "slot" ADD CONSTRAINT "slot_calendarConnectionId_fkey"
    FOREIGN KEY ("calendarConnectionId") REFERENCES "calendar_connection"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "booking" (
    "id" TEXT NOT NULL,
    "referralId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "specialistId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'preference_captured',
    "urgentFastPath" BOOLEAN NOT NULL DEFAULT false,
    "preferredDayOfWeek" TEXT,
    "preferredTimeOfDay" TEXT,
    "slotId" TEXT,
    "confirmedSlotStartsAt" TIMESTAMP(3),
    "confirmedSlotEndsAt" TIMESTAMP(3),
    "slotVersion" INTEGER NOT NULL DEFAULT 0,
    "waitlistedAt" TIMESTAMP(3),
    "cancelledAt" TIMESTAMP(3),
    "cancellationReason" TEXT,
    "externalCalendarEventId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "booking_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "booking_patientId_idx" ON "booking"("patientId");
CREATE INDEX "booking_specialistId_idx" ON "booking"("specialistId");
CREATE INDEX "booking_referralId_idx" ON "booking"("referralId");
CREATE INDEX "booking_status_idx" ON "booking"("status");

CREATE TABLE "waitlist_entry" (
    "id" TEXT NOT NULL,
    "bookingId" TEXT NOT NULL,
    "specialistId" TEXT NOT NULL,
    "preferredDayOfWeek" TEXT,
    "preferredTimeOfDay" TEXT,
    "status" TEXT NOT NULL DEFAULT 'waiting',
    "notifiedAt" TIMESTAMP(3),
    "claimedAt" TIMESTAMP(3),
    "expiredAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "waitlist_entry_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "waitlist_entry_bookingId_key" ON "waitlist_entry"("bookingId");
CREATE INDEX "waitlist_entry_specialistId_status_createdAt_idx" ON "waitlist_entry"("specialistId", "status", "createdAt");

ALTER TABLE "waitlist_entry" ADD CONSTRAINT "waitlist_entry_bookingId_fkey"
    FOREIGN KEY ("bookingId") REFERENCES "booking"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "audit_outbox" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actor" JSONB NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_outbox_publishedAt_idx" ON "audit_outbox"("publishedAt");
