-- Hand-authored to match prisma/schema.prisma's FollowUpPlan, Reminder,
-- DeceasedSuppression, EventPollCursor, and AuditOutbox models.
--
-- Normally this file is generated by `prisma migrate dev --name init` (see
-- root CONVENTIONS.md, "Migration convention"). In this build's sandbox,
-- `prisma generate`/`migrate dev` cannot reach binaries.prisma.sh (blocked
-- by outbound egress policy — confirmed via the agent proxy status endpoint
-- as a policy denial: "Failed to fetch sha256 checksum ... 403 Forbidden",
-- matching the identical, already-documented gap in BUILD_LOG/audit-log.md,
-- BUILD_LOG/identity-access.md, BUILD_LOG/gp-authorisation.md, and
-- BUILD_LOG/consent-security.md). This SQL is written to be byte-for-byte
-- what Prisma would generate for the schema above it, so:
--   1. it can be applied directly (`psql ... -f migration.sql`) to unblock
--      local development/testing right now, and
--   2. once `prisma migrate dev` can run in an environment with real network
--      access, it will detect this migration as already applied (same
--      schema shape) rather than generating a duplicate — or, if preferred,
--      delete this hand-authored file and regenerate from schema.prisma
--      directly. See BUILD_LOG/followup-recall.md for the full explanation.

CREATE TABLE "follow_up_plan" (
    "id" TEXT NOT NULL,
    "referralId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "gpId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "referralType" TEXT NOT NULL,
    "nextReviewDueAt" TIMESTAMP(3) NOT NULL,
    "requiredTests" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "indefiniteReferralApplies" BOOLEAN NOT NULL DEFAULT false,
    "testCompletionDetectedVia" TEXT,
    "testCompletedAt" TIMESTAMP(3),
    "gpCourtesyCallDueAt" TIMESTAMP(3),
    "gpCourtesyCallCompletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "follow_up_plan_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "follow_up_plan_patientId_idx" ON "follow_up_plan"("patientId");
CREATE INDEX "follow_up_plan_status_idx" ON "follow_up_plan"("status");
CREATE INDEX "follow_up_plan_status_nextReviewDueAt_idx" ON "follow_up_plan"("status", "nextReviewDueAt");

CREATE TABLE "reminder" (
    "id" TEXT NOT NULL,
    "followUpPlanId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "recipientType" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "scheduledFor" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'scheduled',
    "escalationLevel" INTEGER NOT NULL DEFAULT 0,
    "sentAt" TIMESTAMP(3),
    "suppressedAt" TIMESTAMP(3),
    "suppressedReason" TEXT,
    "failureReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reminder_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "reminder_followUpPlanId_idx" ON "reminder"("followUpPlanId");
CREATE INDEX "reminder_patientId_idx" ON "reminder"("patientId");
CREATE INDEX "reminder_status_scheduledFor_idx" ON "reminder"("status", "scheduledFor");

ALTER TABLE "reminder" ADD CONSTRAINT "reminder_followUpPlanId_fkey" FOREIGN KEY ("followUpPlanId") REFERENCES "follow_up_plan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "deceased_suppression" (
    "id" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sourceFlagId" TEXT,
    "suppressedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "deceased_suppression_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "deceased_suppression_patientId_key" ON "deceased_suppression"("patientId");

CREATE TABLE "event_poll_cursor" (
    "id" TEXT NOT NULL,
    "lastPolledAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "event_poll_cursor_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "audit_outbox" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actor" JSONB NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_outbox_publishedAt_idx" ON "audit_outbox"("publishedAt");
