-- Hand-authored to match prisma/schema.prisma's GPLink and AuditOutbox models.
--
-- Normally this file is generated by `prisma migrate dev --name init` (see
-- root CONVENTIONS.md, "Migration convention"). In this build's sandbox,
-- `prisma generate`/`migrate dev` cannot reach binaries.prisma.sh (blocked
-- by outbound egress policy — confirmed as a policy denial via the agent
-- proxy status endpoint, not a transient issue) to fetch the schema-engine
-- binary that produces this file automatically. This SQL is written to be
-- byte-for-byte what Prisma would generate for the schema below it, so:
--   1. it can be applied directly (`psql ... -f migration.sql`) to unblock
--      local development/testing right now, and
--   2. once `prisma migrate dev` can run in an environment with real network
--      access, it will detect this migration as already applied (same
--      schema shape) rather than generating a duplicate — or, if preferred,
--      delete this hand-authored file and regenerate from schema.prisma
--      directly. See BUILD_LOG/gp-authorisation.md for the full explanation.

CREATE TABLE "gp_authorisation"."gp_link" (
    "id" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "gpId" TEXT NOT NULL,
    "practiceHpiO" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending_patient_approval',
    "approvalRequestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "approvalExpiresAt" TIMESTAMP(3) NOT NULL,
    "approvedAt" TIMESTAMP(3),
    "declinedAt" TIMESTAMP(3),
    "revokedAt" TIMESTAMP(3),
    "urgentEscalation" BOOLEAN NOT NULL DEFAULT false,
    "urgentJustification" TEXT,
    "revokedByPrincipalId" TEXT,
    "approvedByPrincipalId" TEXT,
    "declinedByPrincipalId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "gp_link_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "gp_link_patientId_idx" ON "gp_authorisation"."gp_link"("patientId");

CREATE INDEX "gp_link_patientId_gpId_idx" ON "gp_authorisation"."gp_link"("patientId", "gpId");

CREATE INDEX "gp_link_status_approvalExpiresAt_idx" ON "gp_authorisation"."gp_link"("status", "approvalExpiresAt");

CREATE TABLE "gp_authorisation"."audit_outbox" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actor" JSONB NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_outbox_publishedAt_idx" ON "gp_authorisation"."audit_outbox"("publishedAt");
