-- Hand-authored to match prisma/schema.prisma's models.
--
-- Normally this file is generated by `prisma migrate dev --name init` (see
-- root CONVENTIONS.md, "Migration convention"). In this build's sandbox,
-- `prisma generate`/`migrate dev` cannot reach binaries.prisma.sh to fetch
-- the schema-engine binary that produces this file automatically (outbound
-- network calls to that host repeatedly failed/timed out via the agent
-- proxy in this session — the same root cause already documented in
-- BUILD_LOG/audit-log.md for this repo). This SQL is written to be
-- byte-for-byte what Prisma would generate for the schema below it, so:
--   1. it can be applied directly (`psql ... -f migration.sql`) to unblock
--      local development/testing right now, and
--   2. once `prisma migrate dev` can run in an environment with real network
--      access, it will detect this migration as already applied (same
--      schema shape) rather than generating a duplicate — or, if preferred,
--      delete this hand-authored file and regenerate from schema.prisma
--      directly. See BUILD_LOG/admin-console.md for the full explanation.

CREATE TABLE "admin_console"."verification_cases" (
    "id" TEXT NOT NULL,
    "caseType" TEXT NOT NULL,
    "entityType" TEXT,
    "entityId" TEXT,
    "subjectName" TEXT NOT NULL,
    "subjectIdentifier" TEXT,
    "issuingState" TEXT,
    "lastKnownAutomatedStatus" TEXT,
    "lastKnownAutomatedDetail" JSONB,
    "lastRefreshedAt" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'open',
    "assignedStaffId" TEXT,
    "notes" TEXT,
    "decisionNote" TEXT,
    "decidedByStaffId" TEXT,
    "decidedAt" TIMESTAMP(3),
    "createdByStaffId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "verification_cases_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "verification_cases_status_idx" ON "admin_console"."verification_cases"("status");
CREATE INDEX "verification_cases_caseType_idx" ON "admin_console"."verification_cases"("caseType");
CREATE INDEX "verification_cases_entityType_entityId_idx" ON "admin_console"."verification_cases"("entityType", "entityId");

CREATE TABLE "admin_console"."practice_onboarding_cases" (
    "id" TEXT NOT NULL,
    "gpPracticeId" TEXT,
    "practiceName" TEXT NOT NULL,
    "hpiO" TEXT,
    "phn" TEXT,
    "state" TEXT,
    "contactName" TEXT,
    "contactEmail" TEXT,
    "contactPhone" TEXT,
    "stage" TEXT NOT NULL DEFAULT 'lead',
    "lastKnownVerificationStatus" TEXT,
    "lastKnownComplianceAckAt" TIMESTAMP(3),
    "lastRefreshedAt" TIMESTAMP(3),
    "integrationTier" TEXT,
    "notes" TEXT,
    "assignedStaffId" TEXT,
    "createdByStaffId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "practice_onboarding_cases_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "practice_onboarding_cases_stage_idx" ON "admin_console"."practice_onboarding_cases"("stage");
CREATE INDEX "practice_onboarding_cases_gpPracticeId_idx" ON "admin_console"."practice_onboarding_cases"("gpPracticeId");

CREATE TABLE "admin_console"."audit_outbox" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actor" JSONB NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "lastError" TEXT,

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_outbox_publishedAt_idx" ON "admin_console"."audit_outbox"("publishedAt");
