-- Hand-authored to match prisma/schema.prisma. See
-- services/gp-authorisation/prisma/migrations/20260813130000_init/migration.sql
-- and BUILD_LOG/consent-security.md for why this is hand-authored rather
-- than generated by `prisma migrate dev` (binaries.prisma.sh is blocked by
-- this sandbox's outbound egress policy).

CREATE TABLE "consent_security"."consent_record" (
    "id" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "sensitiveCategory" TEXT,
    "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "grantedByPrincipalId" TEXT NOT NULL,
    "revokedAt" TIMESTAMP(3),
    "revokedByPrincipalId" TEXT,
    "reattestedAt" TIMESTAMP(3),
    "nextReattestationDueAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "consent_record_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "consent_record_patientId_subjectType_idx" ON "consent_security"."consent_record"("patientId", "subjectType");

CREATE INDEX "consent_record_patientId_subjectType_subjectId_idx" ON "consent_security"."consent_record"("patientId", "subjectType", "subjectId");

CREATE TABLE "consent_security"."reattestation_schedule" (
    "id" TEXT NOT NULL,
    "carerId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "relationship" TEXT NOT NULL,
    "cadenceDays" INTEGER NOT NULL DEFAULT 365,
    "lastReattestedAt" TIMESTAMP(3),
    "nextDueAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reattestation_schedule_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "reattestation_schedule_carerId_patientId_key" ON "consent_security"."reattestation_schedule"("carerId", "patientId");

CREATE INDEX "reattestation_schedule_nextDueAt_idx" ON "consent_security"."reattestation_schedule"("nextDueAt");

CREATE TABLE "consent_security"."concern" (
    "id" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "relatedReferralId" TEXT,
    "category" TEXT NOT NULL,
    "routedTo" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'routed',
    "summary" TEXT NOT NULL,
    "gpNotifiedId" TEXT,
    "raisedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" TIMESTAMP(3),
    "resolutionNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "concern_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "concern_patientId_idx" ON "consent_security"."concern"("patientId");

CREATE INDEX "concern_status_idx" ON "consent_security"."concern"("status");

CREATE TABLE "consent_security"."deceased_flag" (
    "id" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "flaggedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "flaggedByGpId" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "reason" TEXT,
    "freezeConfirmedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "deceased_flag_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "deceased_flag_patientId_key" ON "consent_security"."deceased_flag"("patientId");

CREATE TABLE "consent_security"."access_request" (
    "id" TEXT NOT NULL,
    "deceasedFlagId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "requesterName" TEXT NOT NULL,
    "requesterEmail" TEXT,
    "requesterPhone" TEXT,
    "requesterRelationship" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "evidenceDescription" TEXT,
    "evidenceDocumentId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "reviewedByStaffId" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "decisionNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "access_request_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "access_request_patientId_idx" ON "consent_security"."access_request"("patientId");

CREATE INDEX "access_request_status_idx" ON "consent_security"."access_request"("status");

ALTER TABLE "consent_security"."access_request" ADD CONSTRAINT "access_request_deceasedFlagId_fkey" FOREIGN KEY ("deceasedFlagId") REFERENCES "consent_security"."deceased_flag"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "consent_security"."published_event" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "published_event_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "published_event_type_occurredAt_idx" ON "consent_security"."published_event"("type", "occurredAt");

CREATE INDEX "published_event_patientId_idx" ON "consent_security"."published_event"("patientId");

CREATE TABLE "consent_security"."audit_outbox" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actor" JSONB NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_outbox_publishedAt_idx" ON "consent_security"."audit_outbox"("publishedAt");
