-- Hand-authored to match prisma/schema.prisma's DirectoryEntry,
-- DirectorySyncRun, RoutingAttempt and AuditOutbox models.
--
-- Normally this file is generated by `prisma migrate dev --name init` (see
-- root CONVENTIONS.md, "Migration convention"). In this build's sandbox,
-- `prisma generate`/`migrate dev` cannot reach binaries.prisma.sh (blocked
-- by outbound egress policy — confirmed as a policy denial via the agent
-- proxy status endpoint: `curl "$HTTPS_PROXY/__agentproxy/status"` returns
-- connect_rejected/403 on CONNECT, not a transient issue — identical to the
-- already-documented gap in BUILD_LOG/audit-log.md, BUILD_LOG/identity-access.md
-- and BUILD_LOG/gp-authorisation.md). This SQL is written to be byte-for-byte
-- what Prisma would generate for the schema below it, so:
--   1. it can be applied directly (`psql ... -f migration.sql`) to unblock
--      local development/testing right now, and
--   2. once `prisma migrate dev` can run in an environment with real network
--      access, it will detect this migration as already applied (same
--      schema shape) rather than generating a duplicate — or, if preferred,
--      delete this hand-authored file and regenerate from schema.prisma
--      directly. See BUILD_LOG/directory.md for the full explanation.

CREATE TABLE "directory"."directory_entry" (
    "id" TEXT NOT NULL,
    "specialistId" TEXT,
    "hpiI" TEXT,
    "source" TEXT NOT NULL,
    "selfRegisteredOverride" BOOLEAN NOT NULL DEFAULT false,
    "displayName" TEXT NOT NULL,
    "subspecialty" TEXT NOT NULL,
    "practiceLocations" JSONB NOT NULL,
    "consultingDays" TEXT[],
    "econsultOptIn" BOOLEAN NOT NULL DEFAULT false,
    "acceptsBookingsViaPlatform" BOOLEAN NOT NULL DEFAULT false,
    "onboardedForDirectDelivery" BOOLEAN NOT NULL DEFAULT false,
    "secureMessagingVendor" TEXT,
    "secureMessagingEndpointId" TEXT,
    "lastSyncedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "directory_entry_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "directory_entry_hpiI_key" ON "directory"."directory_entry"("hpiI");

CREATE INDEX "directory_entry_subspecialty_idx" ON "directory"."directory_entry"("subspecialty");

CREATE INDEX "directory_entry_source_idx" ON "directory"."directory_entry"("source");

CREATE TABLE "directory"."directory_sync_run" (
    "id" TEXT NOT NULL,
    "source" TEXT NOT NULL DEFAULT 'nhsd_mock',
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'running',
    "recordsFetched" INTEGER NOT NULL DEFAULT 0,
    "recordsUpserted" INTEGER NOT NULL DEFAULT 0,
    "recordsSkippedSelfRegistered" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,

    CONSTRAINT "directory_sync_run_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "directory_sync_run_startedAt_idx" ON "directory"."directory_sync_run"("startedAt");

CREATE TABLE "directory"."routing_attempt" (
    "id" TEXT NOT NULL,
    "referralId" TEXT NOT NULL,
    "directoryEntryId" TEXT,
    "method" TEXT NOT NULL,
    "vendor" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attemptNumber" INTEGER NOT NULL DEFAULT 1,
    "failureReason" TEXT,
    "vendorMessageId" TEXT,
    "attemptedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" TIMESTAMP(3),

    CONSTRAINT "routing_attempt_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "routing_attempt_referralId_idx" ON "directory"."routing_attempt"("referralId");

CREATE INDEX "routing_attempt_status_idx" ON "directory"."routing_attempt"("status");

CREATE TABLE "directory"."audit_outbox" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "actor" JSONB NOT NULL,
    "subjectType" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMP(3),

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_outbox_publishedAt_idx" ON "directory"."audit_outbox"("publishedAt");
